import { normalizeVenue } from '../normalize/normalizeVenue'
import type { RawPlace } from '../types/rawPlace'
import type { Venue } from '../types/venue'

const ENABLED_VALUES = new Set(['1', 'true', 'on'])

export const devGreatStopFixtureRawPlaces: RawPlace[] = [
  {
    rawType: 'place',
    id: 'dev_fixture_sofa_social_cafe',
    name: 'SoFA Social Cafe',
    city: 'San Jose',
    neighborhood: 'SoFA District',
    driveMinutes: 8,
    priceTier: '$$',
    tags: ['coffee', 'social', 'local', 'walkable', 'warmup'],
    shortDescription: 'Social cafe start with walkable pre-show energy.',
    narrativeFlavor: 'A friendly opening stop that warms up a music-forward night.',
    imageUrl: '',
    isActive: true,
    categoryHint: 'cafe',
    subcategoryHint: 'social-cafe',
    sourceTypes: ['cafe', 'coffee', 'social'],
    normalizedFromRawType: 'seed',
    sourceOrigin: 'curated',
    curatedSubtype: 'seed',
    providerRecordId: 'dev-great-stop-sofa-social-cafe',
    sourceQueryLabel: 'dev-great-stop-fixture',
    openNow: true,
    latitude: 37.3293,
    longitude: -121.8893,
  },
  {
    rawType: 'place',
    id: 'dev_fixture_record_row_small_plates',
    name: 'Record Row Small Plates',
    city: 'San Jose',
    neighborhood: 'SoFA District',
    driveMinutes: 9,
    priceTier: '$$',
    tags: ['small-plates', 'social', 'local', 'pre-show'],
    shortDescription: 'Low-friction bar start suited to pre-show conversation.',
    narrativeFlavor: 'A social warmup with enough momentum to feed into live music.',
    imageUrl: '',
    isActive: true,
    categoryHint: 'bar',
    subcategoryHint: 'small-plates-bar',
    sourceTypes: ['bar', 'small-plates', 'social'],
    normalizedFromRawType: 'seed',
    sourceOrigin: 'curated',
    curatedSubtype: 'seed',
    providerRecordId: 'dev-great-stop-record-row-small-plates',
    sourceQueryLabel: 'dev-great-stop-fixture',
    openNow: true,
    latitude: 37.3301,
    longitude: -121.8878,
  },
  {
    rawType: 'place',
    id: 'dev_fixture_theatre_district_jazz_cellar',
    name: 'Theatre District Jazz Cellar',
    city: 'San Jose',
    neighborhood: 'Downtown San Jose',
    driveMinutes: 10,
    priceTier: '$$',
    tags: ['jazz', 'listening', 'live', 'local-artists', 'small-stage'],
    shortDescription: 'Listening-room highlight with local jazz programming.',
    narrativeFlavor: 'A sound-forward centerpiece built for live performance and focus.',
    imageUrl: '',
    isActive: true,
    categoryHint: 'live_music',
    subcategoryHint: 'jazz-cellar',
    sourceTypes: ['live_music', 'jazz', 'performance'],
    normalizedFromRawType: 'seed',
    sourceOrigin: 'curated',
    curatedSubtype: 'seed',
    providerRecordId: 'dev-great-stop-theatre-district-jazz-cellar',
    openNow: true,
    latitude: 37.3332,
    longitude: -121.8898,
    musicCapable: true,
    performanceCapable: true,
    eventCapable: true,
  },
  {
    rawType: 'place',
    id: 'dev_fixture_riverwalk_indie_showcase',
    name: 'Riverwalk Indie Showcase',
    city: 'San Jose',
    neighborhood: 'Downtown San Jose',
    driveMinutes: 11,
    priceTier: '$$',
    tags: ['indie', 'live-music', 'immersive', 'community', 'social'],
    shortDescription: 'Indie event room with walkable social spillover.',
    narrativeFlavor: 'An immersive local-music node designed to anchor a lively night.',
    imageUrl: '',
    isActive: true,
    categoryHint: 'event',
    subcategoryHint: 'indie-showcase',
    sourceTypes: ['event', 'live-music', 'community'],
    normalizedFromRawType: 'seed',
    sourceOrigin: 'curated',
    curatedSubtype: 'seed',
    providerRecordId: 'dev-great-stop-riverwalk-indie-showcase',
    openNow: true,
    latitude: 37.335,
    longitude: -121.8921,
    musicCapable: true,
    performanceCapable: true,
    eventCapable: true,
  },
  {
    rawType: 'place',
    id: 'dev_fixture_vinyl_dj_lounge',
    name: 'Vinyl DJ Lounge',
    city: 'San Jose',
    neighborhood: 'SoFA District',
    driveMinutes: 10,
    priceTier: '$$',
    tags: ['dj', 'listening', 'social', 'night', 'immersive'],
    shortDescription: 'DJ-led lounge with strong music identity and social energy.',
    narrativeFlavor: 'A nightlife highlight that keeps the route sound-first without needing a large venue.',
    imageUrl: '',
    isActive: true,
    categoryHint: 'bar',
    subcategoryHint: 'vinyl-lounge',
    sourceTypes: ['bar', 'dj', 'nightlife'],
    normalizedFromRawType: 'seed',
    sourceOrigin: 'curated',
    curatedSubtype: 'seed',
    providerRecordId: 'dev-great-stop-vinyl-dj-lounge',
    openNow: true,
    latitude: 37.3288,
    longitude: -121.8869,
    musicCapable: true,
    performanceCapable: true,
  },
  {
    rawType: 'place',
    id: 'dev_fixture_nightcap_lounge',
    name: 'Nightcap Lounge',
    city: 'San Jose',
    neighborhood: 'Downtown San Jose',
    driveMinutes: 10,
    priceTier: '$$',
    tags: ['nightcap', 'social', 'linger', 'low-key'],
    shortDescription: 'Low-key lounge suited to a post-show landing.',
    narrativeFlavor: 'A decompression stop that keeps the route social after the highlight.',
    imageUrl: '',
    isActive: true,
    categoryHint: 'bar',
    subcategoryHint: 'nightcap-lounge',
    sourceTypes: ['bar', 'nightcap', 'lounge'],
    normalizedFromRawType: 'seed',
    sourceOrigin: 'curated',
    curatedSubtype: 'seed',
    providerRecordId: 'dev-great-stop-nightcap-lounge',
    openNow: true,
    latitude: 37.3344,
    longitude: -121.8906,
  },
  {
    rawType: 'place',
    id: 'dev_fixture_late_matcha_cafe',
    name: 'Late Matcha Cafe',
    city: 'San Jose',
    neighborhood: 'Japantown',
    driveMinutes: 12,
    priceTier: '$$',
    tags: ['late-cafe', 'quiet', 'linger', 'cooldown'],
    shortDescription: 'Late cafe option that works as a softer landing after a louder center.',
    narrativeFlavor: 'A calm cooldown stop for routes that need a gentler close.',
    imageUrl: '',
    isActive: true,
    categoryHint: 'cafe',
    subcategoryHint: 'late-cafe',
    sourceTypes: ['cafe', 'late-cafe', 'cooldown'],
    normalizedFromRawType: 'seed',
    sourceOrigin: 'curated',
    curatedSubtype: 'seed',
    providerRecordId: 'dev-great-stop-late-matcha-cafe',
    openNow: true,
    latitude: 37.3491,
    longitude: -121.8947,
  },
  {
    rawType: 'place',
    id: 'dev_fixture_ramen_after_set',
    name: 'Ramen After Set',
    city: 'San Jose',
    neighborhood: 'Japantown',
    driveMinutes: 12,
    priceTier: '$$',
    tags: ['late-bite', 'local', 'night', 'cooldown'],
    shortDescription: 'Late-bite wind-down that stays viable after a music-forward centerpiece.',
    narrativeFlavor: 'A reliable post-set landing for routes that want food instead of a second peak.',
    imageUrl: '',
    isActive: true,
    categoryHint: 'restaurant',
    subcategoryHint: 'late-bite',
    sourceTypes: ['restaurant', 'late-bite', 'night'],
    normalizedFromRawType: 'seed',
    sourceOrigin: 'curated',
    curatedSubtype: 'seed',
    providerRecordId: 'dev-great-stop-ramen-after-set',
    openNow: true,
    latitude: 37.3484,
    longitude: -121.8941,
  },
]

export const devGreatStopFixtureVenueIds = devGreatStopFixtureRawPlaces.map((fixture) => fixture.id)

export function readDevGreatStopFixturesEnvRaw(): string {
  return String(import.meta.env.VITE_ENABLE_DEV_GREAT_STOP_FIXTURES ?? '')
}

export function readDevGreatStopFixturesEnabled(): boolean {
  const envValue = readDevGreatStopFixturesEnvRaw().trim().toLowerCase()
  return ENABLED_VALUES.has(envValue)
}

export function normalizeDevGreatStopFixtures(): Venue[] {
  return devGreatStopFixtureRawPlaces.map((fixture) => normalizeVenue(fixture))
}
